# Generated by Django 3.1.4 on 2020-12-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
