# Generated by Django 3.1.4 on 2020-12-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_pizza_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='extra_toppings',
            field=models.ManyToManyField(related_name='pizza_orders', to='order.Topping'),
        ),
    ]
