# Generated by Django 3.1.4 on 2020-12-28 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20201228_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_orders', to='order.pizza'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_orders', to='order.size'),
        ),
    ]
